// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXz0TOFEZ-eego_wKyhZPQKqb3ZWArjSc',
    appId: '1:391919209733:web:51b55c76ade6b0a3f87b6c',
    messagingSenderId: '391919209733',
    projectId: 'medic-firebase',
    authDomain: 'medic-firebase.firebaseapp.com',
    storageBucket: 'medic-firebase.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_gdu1Tmgs_69LnJUbegq3vRY-uhtOAIs',
    appId: '1:391919209733:android:16572502f94a4827f87b6c',
    messagingSenderId: '391919209733',
    projectId: 'medic-firebase',
    storageBucket: 'medic-firebase.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHRvGYEe3rKbU429GckpIjWxLgQd8yGKg',
    appId: '1:391919209733:ios:f4b2de7c3eaad18ef87b6c',
    messagingSenderId: '391919209733',
    projectId: 'medic-firebase',
    storageBucket: 'medic-firebase.appspot.com',
    iosBundleId: 'com.example.medics',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCHRvGYEe3rKbU429GckpIjWxLgQd8yGKg',
    appId: '1:391919209733:ios:f4b2de7c3eaad18ef87b6c',
    messagingSenderId: '391919209733',
    projectId: 'medic-firebase',
    storageBucket: 'medic-firebase.appspot.com',
    iosBundleId: 'com.example.medics',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDXz0TOFEZ-eego_wKyhZPQKqb3ZWArjSc',
    appId: '1:391919209733:web:b4446cc9231aec7ff87b6c',
    messagingSenderId: '391919209733',
    projectId: 'medic-firebase',
    authDomain: 'medic-firebase.firebaseapp.com',
    storageBucket: 'medic-firebase.appspot.com',
  );
}
