// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAh3L8WmLFBve7ajYuRI1n4Uu10uT2JQBI',
    appId: '1:695706272849:web:9e1b6ea8ecbd7d85186470',
    messagingSenderId: '695706272849',
    projectId: 'patientpal-system',
    authDomain: 'patientpal-system.firebaseapp.com',
    storageBucket: 'patientpal-system.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-CXVvC2v0Kli4RzbyvGwttvUEuhlixI8',
    appId: '1:695706272849:android:3301a448249373c2186470',
    messagingSenderId: '695706272849',
    projectId: 'patientpal-system',
    storageBucket: 'patientpal-system.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDaEMCEHNHwjfWUIrL0ZdjKY6ZzIhY35EQ',
    appId: '1:695706272849:ios:ab7b245a6c9cbeda186470',
    messagingSenderId: '695706272849',
    projectId: 'patientpal-system',
    storageBucket: 'patientpal-system.appspot.com',
    iosBundleId: 'com.example.patientpalSystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDaEMCEHNHwjfWUIrL0ZdjKY6ZzIhY35EQ',
    appId: '1:695706272849:ios:ab7b245a6c9cbeda186470',
    messagingSenderId: '695706272849',
    projectId: 'patientpal-system',
    storageBucket: 'patientpal-system.appspot.com',
    iosBundleId: 'com.example.patientpalSystem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAh3L8WmLFBve7ajYuRI1n4Uu10uT2JQBI',
    appId: '1:695706272849:web:8f41426382a1dc85186470',
    messagingSenderId: '695706272849',
    projectId: 'patientpal-system',
    authDomain: 'patientpal-system.firebaseapp.com',
    storageBucket: 'patientpal-system.appspot.com',
  );
}
